# nodejs-app.yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  namespace: node-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: ketan32/node-backend  # Replace with your Docker image
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: "mysql-service"  # Replace with your MySQL host
            - name: DB_USER
              value: "admin"  # Replace with your MySQL username
            - name: DB_PASSWORD
              value: "admin"  # Replace with your MySQL password
            - name: DB_NAME
              value: "db1"  # Replace with your MySQL database name
            - name: SECRET_KEY
              value: "secretKey"
            - name: REFRESH_TOKEN_SECRET
              value: "secretRefreshKey"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service  # Name of the service
  namespace: node-backend
spec:
  selector:
    app: nodejs-app  # Selectors matching labels in Deployment
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service (on all nodes)
      targetPort: 3001  # Port on the container to forward traffic to
#      nodePort: 30080  # Port accessible externally on all nodes
  type: NodePort  # Type of service (NodePort for external access)


