apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
  namespace: aadil
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-backend2
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10

