apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
        #      nodePort: 30001  # You can choose any available port in the range 30000-32767
  selector:
    app: kibana

